CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  tg_id BIGINT UNIQUE NOT NULL,
  username TEXT,
  first_name TEXT,
  foxes NUMERIC NOT NULL DEFAULT 25000,
  crystals NUMERIC NOT NULL DEFAULT 0,
  bank NUMERIC NOT NULL DEFAULT 0,
  xp INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  energy INT NOT NULL DEFAULT 10,
  vip_level INT NOT NULL DEFAULT 0,
  vip_until TIMESTAMP,
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  referrer_id INT REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_bonus_at TIMESTAMP,
  last_work_at TIMESTAMP,
  last_luck_at TIMESTAMP,
  garden_watered_at TIMESTAMP,
  income_boost_until TIMESTAMP,
  case_luck_until TIMESTAMP,
  luck_charges INT NOT NULL DEFAULT 0,
  pass_premium BOOLEAN NOT NULL DEFAULT FALSE,
  pass_xp INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_users_tg_id ON users(tg_id);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(LOWER(username));
CREATE INDEX IF NOT EXISTS idx_users_foxes ON users(foxes DESC);
CREATE INDEX IF NOT EXISTS idx_users_level ON users(level DESC);

CREATE TABLE IF NOT EXISTS promo_codes (
  id SERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  reward_foxes NUMERIC NOT NULL DEFAULT 0,
  reward_crystals NUMERIC NOT NULL DEFAULT 0,
  max_activations INT NOT NULL,
  activations INT NOT NULL DEFAULT 0,
  min_level INT NOT NULL DEFAULT 1,
  only_new BOOLEAN NOT NULL DEFAULT FALSE,
  only_vip BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promo_activations (
  id SERIAL PRIMARY KEY,
  promo_id INT NOT NULL REFERENCES promo_codes(id) ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(promo_id, user_id)
);

CREATE TABLE IF NOT EXISTS marriages (
  id SERIAL PRIMARY KEY,
  user1_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user2_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user1_id),
  UNIQUE(user2_id),
  CHECK (user1_id <> user2_id)
);

CREATE TABLE IF NOT EXISTS user_cases (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  case_id INT NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  UNIQUE(user_id, case_id)
);

CREATE TABLE IF NOT EXISTS facilities (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  level INT NOT NULL DEFAULT 1,
  income NUMERIC NOT NULL DEFAULT 0,
  title TEXT NOT NULL,
  last_collect_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  video_cards INT NOT NULL DEFAULT 0,
  max_video_cards INT NOT NULL DEFAULT 10,
  tax_debt NUMERIC NOT NULL DEFAULT 0,
  tax_limit NUMERIC NOT NULL DEFAULT 5000000,
  account NUMERIC NOT NULL DEFAULT 0,
  last_tick_at TIMESTAMP,
  territory_m2 INT NOT NULL DEFAULT 120,
  business_m2 INT NOT NULL DEFAULT 120,
  trees_count INT NOT NULL DEFAULT 10,
  water INT NOT NULL DEFAULT 100,
  max_water INT NOT NULL DEFAULT 100,
  UNIQUE(user_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_facilities_user_kind ON facilities(user_id, kind);

CREATE TABLE IF NOT EXISTS inventory_items (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,
  title TEXT NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(user_id, item_key)
);
CREATE INDEX IF NOT EXISTS idx_inventory_items_user ON inventory_items(user_id);

CREATE TABLE IF NOT EXISTS clans (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  owner_user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank NUMERIC NOT NULL DEFAULT 0,
  xp INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clan_members (
  id SERIAL PRIMARY KEY,
  clan_id INT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS market_lots (
  id SERIAL PRIMARY KEY,
  seller_user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,
  title TEXT NOT NULL,
  amount INT NOT NULL DEFAULT 1,
  price NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sold_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_market_active ON market_lots(status, created_at DESC);

CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE SET NULL,
  kind TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  meta TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tx_created ON transactions(created_at DESC);

CREATE TABLE IF NOT EXISTS daily_progress (
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL DEFAULT CURRENT_DATE,
  bonus_done BOOLEAN NOT NULL DEFAULT FALSE,
  casino_count INT NOT NULL DEFAULT 0,
  collect_done BOOLEAN NOT NULL DEFAULT FALSE,
  garden_done BOOLEAN NOT NULL DEFAULT FALSE,
  case_done BOOLEAN NOT NULL DEFAULT FALSE,
  claimed BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY(user_id, day)
);

CREATE TABLE IF NOT EXISTS pass_rewards (
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  level INT NOT NULL,
  premium BOOLEAN NOT NULL DEFAULT FALSE,
  claimed_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY(user_id, level, premium)
);

CREATE TABLE IF NOT EXISTS cooldowns (
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  used_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY(user_id, key)
);

-- ===== AUTO-MIGRATIONS FOR OLDER DATABASES =====
-- These ALTER statements make old Railway/PostgreSQL databases compatible with the current code.
-- CREATE TABLE IF NOT EXISTS does not add new columns to existing tables, so we keep migrations here.

ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS foxes NUMERIC NOT NULL DEFAULT 25000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS crystals NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS xp INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS energy INT NOT NULL DEFAULT 10;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vip_level INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vip_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referrer_id INT REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_bonus_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_work_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_luck_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS garden_watered_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS income_boost_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS case_luck_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS luck_charges INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pass_premium BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pass_xp INT NOT NULL DEFAULT 0;

DO $$
BEGIN
  -- If the very first bot version used "balance" instead of "foxes", copy balances once.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='users' AND column_name='balance'
  ) THEN
    EXECUTE 'UPDATE users SET foxes = COALESCE(foxes, balance, 25000)';
  END IF;

  -- If the early bot used "bcoins", copy them into crystals when crystals are empty.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='users' AND column_name='bcoins'
  ) THEN
    EXECUTE 'UPDATE users SET crystals = COALESCE(NULLIF(crystals, 0), bcoins, 0)';
  END IF;
END $$;

ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS reward_foxes NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS reward_crystals NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS max_activations INT NOT NULL DEFAULT 1;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS activations INT NOT NULL DEFAULT 0;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS min_level INT NOT NULL DEFAULT 1;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS only_new BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS only_vip BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;
ALTER TABLE promo_codes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promo_codes' AND column_name='reward_balance') THEN
    EXECUTE 'UPDATE promo_codes SET reward_foxes = COALESCE(NULLIF(reward_foxes,0), reward_balance, 0)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promo_codes' AND column_name='reward_bcoins') THEN
    EXECUTE 'UPDATE promo_codes SET reward_crystals = COALESCE(NULLIF(reward_crystals,0), reward_bcoins, 0)';
  END IF;
END $$;

ALTER TABLE facilities ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 1;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS income NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Постройка';
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS last_collect_at TIMESTAMP;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS video_cards INT NOT NULL DEFAULT 0;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS max_video_cards INT NOT NULL DEFAULT 10;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS tax_debt NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS tax_limit NUMERIC NOT NULL DEFAULT 5000000;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS account NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS last_tick_at TIMESTAMP;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS territory_m2 INT NOT NULL DEFAULT 120;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS business_m2 INT NOT NULL DEFAULT 120;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS trees_count INT NOT NULL DEFAULT 10;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS water INT NOT NULL DEFAULT 100;
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS max_water INT NOT NULL DEFAULT 100;

ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS bonus_done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS casino_count INT NOT NULL DEFAULT 0;
ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS collect_done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS garden_done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS case_done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE daily_progress ADD COLUMN IF NOT EXISTS claimed BOOLEAN NOT NULL DEFAULT FALSE;
